server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: datascope
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datascope?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: tZ_,\;qP1\?CtV

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.datascope.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
    defaultModelExpandDepth: 3
    displayRequestDuration: true
    filter: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: 
    - com.datascope.api.controller
    - com.datascope.controller
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json