spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/datascope_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test_user
    password: test_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1

  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 1  # 使用单独的数据库
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 服务器配置
server:
  port: 8081  # 使用不同的端口
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: INFO
    com.datascope: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    path: ./logs
    name: datascope-test.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 应用配置
datascope:
  cache:
    query-result-ttl: 3600
  datasource:
    connection-timeout: 30000
    validation-timeout: 5000
    max-lifetime: 1800000

# Swagger配置
springfox:
  documentation:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    open-api:
      enabled: true
      path: /v3/api-docs