spring:
  application:
    name: datascope
  
  profiles:
    active: secret
  
  # Swagger配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/datascope?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false  # 生产环境关闭SQL日志
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false  # 生产环境关闭SQL格式化
  
  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: INFO
    com.datascope: INFO  # 调整为INFO级别
    org.hibernate.SQL: INFO  # 调整为INFO级别
    org.hibernate.type.descriptor.sql.BasicBinder: INFO  # 调整为INFO级别

# 应用配置
datascope:
  cache:
    query-result-ttl: 3600
  datasource:
    connection-timeout: 30000
    validation-timeout: 5000
    max-lifetime: 1800000

# Swagger配置
springfox:
  documentation:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    open-api:
      enabled: true
      path: /v3/api-docs