spring:
  main:
    allow-bean-definition-overriding: true
  # Flyway配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1.0.0
    validate-on-migrate: true
    clean-disabled: true
    table: flyway_schema_history
    out-of-order: false
    placeholder-replacement: false

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/datascope?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: tZ_,;qP1?CtV
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      auto-commit: true
      pool-name: DataScopeHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 服务器配置
server:
  port: 8082
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: INFO
    com.datascope: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    path: ./logs
    name: datascope-dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 应用配置
datascope:
  cache:
    query-result-ttl: 3600
  datasource:
    connection-timeout: 30000
    validation-timeout: 5000
    max-lifetime: 1800000

# springdoc-openapi 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**
  packages-to-scan: com.datascope.facade.controller