spring:
  application:
    name: datascope
  
  profiles:
    active: dev
  
  # Swagger配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/datascope?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: datascope
    password: "Datascope@123"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  
  # Flyway配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false  # 生产环境关闭SQL格式化
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: INFO
    com.datascope: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: INFO  # 调整为INFO级别
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB

# 应用配置
datascope:
  cache:
    query-result-ttl: 3600
  datasource:
    connection-timeout: 30000
    validation-timeout: 5000
    max-lifetime: 1800000
  jwt:
    secret: your-secret-key
    expiration: 86400000

# 安全配置
security:
  headers:
    frame-options: DENY
    content-type-options: nosniff
    xss-protection: 1; mode=block
    strict-transport-security: max-age=31536000; includeSubDomains
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true
    max-age: 3600
  rate-limit:
    enabled: true
    requests-per-minute: 60
    burst-size: 100

# Swagger配置
springfox:
  documentation:
    enabled: true
    swagger:
      v2:
        path: /v2/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    auto-startup: true