openapi: 3.0.1
info:
  title: DataScope数据源管理API
  description: 提供数据源的增删改查接口
  version: 1.0.0

tags:
  - name: 数据源管理
    description: 数据源的增删改查接口

paths:
  /api/v1/datasources:
    post:
      tags:
        - 数据源管理
      summary: 创建数据源
      operationId: createDataSource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDataSourceRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSourceResponse'
        '400':
          description: 请求参数错误
        '500':
          description: 服务器内部错误
    
    get:
      tags:
        - 数据源管理
      summary: 获取所有数据源
      operationId: getAllDataSources
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSourceResponse'
        '500':
          description: 服务器内部错误

  /api/v1/datasources/{id}:
    get:
      tags:
        - 数据源管理
      summary: 获取数据源详情
      operationId: getDataSource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: 数据源ID
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSourceResponse'
        '404':
          description: 数据源不存在
        '500':
          description: 服务器内部错误

    put:
      tags:
        - 数据源管理
      summary: 更新数据源
      operationId: updateDataSource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: 数据源ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDataSourceRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSourceResponse'
        '400':
          description: 请求参数错误
        '404':
          description: 数据源不存在
        '500':
          description: 服务器内部错误

    delete:
      tags:
        - 数据源管理
      summary: 删除数据源
      operationId: deleteDataSource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: 数据源ID
      responses:
        '200':
          description: 成功
        '404':
          description: 数据源不存在
        '500':
          description: 服务器内部错误

  /api/v1/datasources/test-connection:
    post:
      tags:
        - 数据源管理
      summary: 测试数据源连接
      operationId: testConnection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestConnectionRequest'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: 请求参数错误
        '500':
          description: 服务器内部错误

components:
  schemas:
    CreateDataSourceRequest:
      type: object
      required:
        - name
        - type
        - host
        - port
        - databaseName
        - username
        - password
      properties:
        name:
          type: string
          description: 数据源名称
          maxLength: 100
        type:
          type: string
          enum: [MYSQL, DB2]
          description: 数据源类型
        host:
          type: string
          description: 主机地址
          maxLength: 255
        port:
          type: integer
          description: 端口号
        databaseName:
          type: string
          description: 数据库名称
          maxLength: 100
        username:
          type: string
          description: 用户名
          maxLength: 100
        password:
          type: string
          description: 密码
          maxLength: 255
        parameters:
          type: string
          description: 连接参数（JSON格式）
        description:
          type: string
          description: 描述
          maxLength: 500

    UpdateDataSourceRequest:
      type: object
      required:
        - name
        - type
        - host
        - port
        - databaseName
        - username
        - password
      properties:
        name:
          type: string
          description: 数据源名称
          maxLength: 100
        type:
          type: string
          enum: [MYSQL, DB2]
          description: 数据源类型
        host:
          type: string
          description: 主机地址
          maxLength: 255
        port:
          type: integer
          description: 端口号
        databaseName:
          type: string
          description: 数据库名称
          maxLength: 100
        username:
          type: string
          description: 用户名
          maxLength: 100
        password:
          type: string
          description: 密码
          maxLength: 255
        parameters:
          type: string
          description: 连接参数（JSON格式）
        description:
          type: string
          description: 描述
          maxLength: 500

    DataSourceResponse:
      type: object
      properties:
        id:
          type: string
          description: 数据源ID
        name:
          type: string
          description: 数据源名称
        type:
          type: string
          enum: [MYSQL, DB2]
          description: 数据源类型
        host:
          type: string
          description: 主机地址
        port:
          type: integer
          description: 端口号
        databaseName:
          type: string
          description: 数据库名称
        username:
          type: string
          description: 用户名
        parameters:
          type: string
          description: 连接参数（JSON格式）
        description:
          type: string
          description: 描述
        createdAt:
          type: string
          format: date-time
          description: 创建时间
        updatedAt:
          type: string
          format: date-time
          description: 更新时间
        createdBy:
          type: string
          description: 创建人
        updatedBy:
          type: string
          description: 更新人

    TestConnectionRequest:
      type: object
      required:
        - type
        - host
        - port
        - databaseName
        - username
        - password
      properties:
        type:
          type: string
          enum: [MYSQL, DB2]
          description: 数据源类型
        host:
          type: string
          description: 主机地址
        port:
          type: integer
          description: 端口号
        databaseName:
          type: string
          description: 数据库名称
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码
        parameters:
          type: string
          description: 连接参数（JSON格式）